### ISSUE TITLE
How to select NPU instead of GPU on Intel laptop?

### ISSUE THREAD

**Issue by mmaitre314** [microsoft/onnxruntime-genai#1029]
Where could I find a code sample showing how to run genai on NPU instead of GPU using `DmlExecutionProvider` in Python?

Conda environment:
```yaml
name: phi3-onnx-dml
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - vs2015_runtime=14.40.33810
  - pip
  - pip:
    - ipykernel==6.29.5
    - numpy==1.26.4
    - huggingface-hub[cli]==0.26.2
    - onnxruntime-directml==1.20.0
    - onnxruntime-genai-directml==0.4.0
```
